apiVersion: v1
kind: Service
metadata:
  name: bold-hypatia-104b45d078-srv
  namespace: apps-prod
spec:
  selector:
    app: bold-hypatia-104b45d078
  ports:
    - protocol: TCP
      port: 80
      targetPort: 7070
  type: ClusterIP